testing_mode = true
payment_provider = "stripe" #bmac if using Buy Me A Coffee
stripe_api_key_test = "rk_test_51P667uJmsKJojwk5PMvhVtI4xx6P0g51gW1SJhoSaiMPbwH7BVl94TtFdFBwMcSVEYkO3ucl0XLYk6InKF7GUApr00EFZXqBRL" #only needed if using Stripe
stripe_api_key = "sk_live_..." #only needed if using Stripe
stripe_link = "https://buy.stripe.com/..." #only needed if using Stripe
stripe_link_test = "https://buy.stripe.com/test_fZeeXJ4st82mb9S8ww" #only needed if using Stripe
client_id = "719957259208-a110qmbhue4lhor9rbk3qcfhm56for1k.apps.googleusercontent.com"
client_secret = "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"
redirect_url_test = 'http://localhost:8501/'
redirect_url = "https://alice-predictions.streamlit.app/"

[connections.mongodb]
url="mongodb+srv://nicolasgilloppe:s0S8eaYt0mIMdYE7@alicedb.eqrplwk.mongodb.net/"
database="alicedb"
collection="Alicetest"